// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: MessageType.capnp

#include "MessageType.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<33> b_a8ec75950d566311 = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
     17,  99,  86,  13, 149, 117, 236, 168,
     18,   0,   0,   0,   1,   0,   0,   0,
    228,  44, 192, 114, 133, 133, 219, 255,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 242,   0,   0,   0,
     33,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     77, 101, 115, 115,  97, 103, 101,  84,
    121, 112, 101,  46,  99,  97, 112, 110,
    112,  58,  77, 101, 115, 115,  97, 103,
    101,  84, 121, 112, 101,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  34,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    109, 115, 103,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_a8ec75950d566311 = b_a8ec75950d566311.words;
#if !CAPNP_LITE
static const uint16_t m_a8ec75950d566311[] = {0};
static const uint16_t i_a8ec75950d566311[] = {0};
const ::capnp::_::RawSchema s_a8ec75950d566311 = {
  0xa8ec75950d566311, b_a8ec75950d566311.words, 33, nullptr, m_a8ec75950d566311,
  0, 1, i_a8ec75950d566311, nullptr, nullptr, { &s_a8ec75950d566311, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
}  // namespace schemas
}  // namespace capnp

// =======================================================================================


// MessageType
constexpr uint16_t MessageType::_capnpPrivate::dataWordSize;
constexpr uint16_t MessageType::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
constexpr ::capnp::Kind MessageType::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* MessageType::_capnpPrivate::schema;
#endif  // !CAPNP_LITE



