//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//
#ifndef RIAPS_FW_COMPTWO_H
#define RIAPS_FW_COMPTWO_H

#include <base/CompTwoBase.h>
#include "common.h"

namespace groupmsgtest {
  namespace components {

    class CompTwo : public CompTwoBase {

    public:
        CompTwo(const py::object *parent_actor,
                const py::dict actor_spec, // Actor json config
                const py::dict type_spec,  // component json config
                const py::list group_spec,
                const std::string &name,
                const std::string &type_name,
                const py::dict args,
                const std::string &application_name,
                const std::string &actor_name);

        virtual void OnClock();
        virtual ~CompTwo() = default;

    private:
        bool m_joinedToA;
        bool m_joinedToB;
    };
  } // namespace components
} // namespace groupmsgtest

std::unique_ptr<groupmsgtest::components::CompTwo>
create_component_py(const py::object *parent_actor,
                    const py::dict actor_spec,
                    const py::dict type_spec,
                    const py::list group_spec,
                    const std::string &name,
                    const std::string &type_name,
                    const py::dict args,
                    const std::string &application_name,
                    const std::string &actor_name);

#endif // RIAPS_FW_COMPTWO_H
